# Policy iteration

In [ ]:
def policy_iteration(S, A, r, gamma, P):
  policy_old = np.zeros(len(S), dtype = 'int') #indexes of actions
  while True:
    b = np.zeros(len(S))
    A_matrix = []
    for i in range(len(S)):
      action = A[policy_old[i]]
      state = int(S[i])
      b[i] =  r(state, action)
      # print(action, state, b[i])
      
      A_row = P[policy_old[i]][i]*gamma
      A_matrix.append(A_row)


    A_matrix = np.identity(len(S)) - A_matrix
    A_matrix = np.array(A_matrix)
    v = np.linalg.solve(A_matrix, b)
    # print(v)

    policy_new = np.zeros(len(S), dtype = 'int')
    for j in range(len(S)):
      rewards_for_action = np.zeros(len(A))

      for k in range(len(A)):
        state = S[j]
        action = A[k]
        rewards_for_action[k] = r(state, action) + gamma*np.dot(P[k][j], v)
        
      policy_new[j] = np.argmax(rewards_for_action)

    # print(policy_new)
    if sum(policy_new == policy_old) == len(S):
      print("entered")
      break
    
    policy_old = policy_new.copy()
  
  return policy_old

# Problem for Policy Iteration

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
def r(s, a):
  return s + a*a

In [ ]:
S = [1, 2, 3]
S = np.array(S)
A = [1, 2]
A = np.array(A)
gamma = 0.7

In [ ]:
P_one = [[0.1, 0.1, 0.8], 
         [0.2, 0.3, 0.5], 
         [0.8, 0.1, 0.1]]
P_two = [[0.8, 0.1, 0.1], 
         [0.6, 0.2, 0.2], 
         [0.2, 0.1, 0.7]]
P = [P_one, P_two]
P = np.array(P)

In [ ]:
np.multiply(P[0][0], [1, 2, 3])

array([0.1, 0.2, 2.4])

In [ ]:
policy  = policy_iteration(S, A, r, gamma, P) #policy array gives indexes of actions we need to access A using these indexes

entered


In [ ]:
policy

array([1, 1, 1])

# Value iteration

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
# value_old = zeros(length(state_space), 1);
value_old = np.zeros((len(S)))
value_new = np.zeros(value_old.shape)
policy = np.zeros((len(value_old)))

In [ ]:
policy.shape

(3,)

In [ ]:
value_new.shape

(3,)

In [ ]:
def value_iteration(S, A, r, gamma, P, tol = 0.01):
  value_old = np.zeros((len(S)))
  value_new = np.zeros(value_old.shape)

  policy = np.zeros((len(value_old)))
  # tol = 0.01
  i = 0
  while True:
    # i = i+1
    # if i == 3:
    #   break
    # print("value_old", value_old)
    for s in range(len(S)):
      reward_for_action = np.zeros((len(A),))
      # print(reward_for_action)
      for a in range(len(A)):
        state = S[s]
        action = A[a]
        # print(a, reward_for_action[a])
        # print(P[a][s])
        # print(value_old)
        reward_for_action[a] = r(state, action) + gamma*np.dot(P[a][s], value_old)
        
      # print(f"reward for action at state {s}:", reward_for_action)
      policy[s] = np.argmax(reward_for_action)
      value_new[s] = np.max(reward_for_action)
    # print(f"Value new at {i}:", value_new)
      
    if max(value_new - value_old) < tol:
      break
    value_old = value_new.copy()
    # print(value_old)
  return value_old

## Problem for Value Iteration

grid problem

0 1 2

3 4 5

6 7 8

In [ ]:
import numpy as np

# Define the state space
S = [0, 1, 2, 3, 4, 5, 6, 7, 8]

# Define the action space
A = ['up', 'down', 'left', 'right']

# Define the reward function
def r(s, a):
    if s == 8:
        return 10
    else:
        return -1

# Define the transition probabilities
P = np.zeros((len(A), len(S), len(S)))
for i in range(len(S)):
    for j in range(len(A)):
        if A[j] == 'up':
            if i < 3:
                P[j,i,i] = 1
            else:
                P[j,i,i-3] = 1
        elif A[j] == 'down':
            if i > 5:
                P[j,i,i] = 1
            else:
                P[j,i,i+3] = 1
        elif A[j] == 'left':
            if i % 3 == 0:
                P[j,i,i] = 1
            else:
                P[j,i,i-1] = 1
        elif A[j] == 'right':
            if i % 3 == 2:
                P[j,i,i] = 1
            else:
                P[j,i,i+1] = 1
# Define the discount factor
gamma = 0.9

# Set the tolerance level
tol = 0.01

# Run the value iteration algorithm
value_estimates = value_iteration(S, A, r, gamma, P, tol)


In [ ]:
value_estimates.reshape((3,3))

array([[62.0754995, 70.0944995, 79.0044995],
       [70.0944995, 79.0044995, 88.9044995],
       [79.0044995, 88.9044995, 99.9044995]])